---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: invidious
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: invidious-secret
    template:
      engineVersion: v2
      data:
        INVIDIOUS_CONFIG: |
          db:
            dbname: {{ .IV_DB_NAME }}
            user: {{ .IV_DB_USER }}
            password: {{ .IV_DB_PASS }}
            host: postgres16-rw.database.svc.cluster.local
            port: 5432
          check_tables: true
          hmac_key: "{{ .IV_HMAC_KEY }}"
        INIT_POSTGRES_DBNAME: "{{ .IV_DB_NAME }}"
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .IV_DB_USER }}"
        INIT_POSTGRES_PASS: "{{ .IV_DB_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: invidious
    - extract:
        key: cloudnative-pg
