---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shlink
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: shlink-secret
    template:
      engineVersion: v2
      data:
        DB_DRIVER: "postgres"
        DB_NAME: &dbName "{{ .SHLINK_DB_NAME }}"
        DB_USER: &dbUser "{{ .SHLINK_DB_USER }}"
        DB_PASSWORD: &dbPass "{{ .SHLINK_DB_PASSWORD }}"
        DB_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        GEOLITE_LICENSE_KEY: "{{ .GEOLITE_LICENSE_KEY }}"
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: shlink
    - extract:
        key: cloudnative-pg
