---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.1.0
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      minio:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: quay.io/minio/minio
              tag: latest
            env:
              MINIO_API_CORS_ALLOW_ORIGIN: https://minio.the-nebula.xyz,https://s3.the-nebula.xyz
              MINIO_BROWSER_REDIRECT_URL: https://minio.the-nebula.xyz
              MINIO_SERVER_URL: https://s3.the-nebula.xyz
              MINIO_UPDATE: "off"
              MINIO_PROMETHEUS_JOB_ID: minio
              MINIO_PROMETHEUS_URL: https://prometheus.the-nebula.xyz
              MINIO_PROMETHEUS_AUTH_TYPE: public
            envFrom:
              - secretRef:
                  name: minio-secret
            args: ["server", "/data", "--console-address", ":9001"]
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /minio/health/live
                    port: 9000
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 6
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - "ALL"
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 10000
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
        controller: minio
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 192.168.3.105
        ports:
          http:
            port: 9001
          s3:
            port: 9000
    serviceMonitor:
      app:
        serviceName: minio
        endpoints:
          - port: s3
            scheme: http
            path: /minio/v2/metrics/cluster
            interval: 1m
            scrapeTimeout: 10s
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.the-nebula.xyz
        hosts:
          - host: "{{ .Release.Name }}.the-nebula.xyz"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
          - host: s3.the-nebula.xyz
            paths:
              - path: /
                service:
                  identifier: app
                  port: s3
    persistence:
      config:
        type: nfs
        server: 192.168.3.5
        path: /eros/Apps/MinIO
        globalMounts:
          - path: /data
