---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name twingate-connector-kube-1-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        ACCESS_TOKEN: "{{ .CONNECTOR_KUBE_1_ACCESS_TOKEN }}"
        REFRESH_TOKEN: "{{ .CONNECTOR_KUBE_1_REFRESH_TOKEN }}"
  dataFrom:
    - extract:
        key: twingate
