---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app twingate-connector-kube-1
spec:
  interval: 30m
  chart:
    spec:
      chart: connector
      version: 0.1.24
      sourceRef:
        kind: HelmRepository
        name: twingate
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
    - targetPath: connector.accessToken
      kind: Secret
      name: twingate-connector-kube-1-secret
      valuesKey: ACCESS_TOKEN
    - targetPath: connector.refreshToken
      kind: Secret
      name: twingate-connector-kube-1-secret
      valuesKey: REFRESH_TOKEN
  values:
    connector:
      network: "kinzoku"
