---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nextcloud-secret
    template:
      engineVersion: v2
      data:
        POSTGRES_DB: &dbName "{{ .NC_POSTGRES_DB }}"
        POSTGRES_USER: &dbUser "{{ .NC_POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .NC_POSTGRES_PASS }}"
        POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        REDIS_HOST: dragonfly.database.svc.cluster.local:6379
        REDIS_HOST_PORT: "6379"
        NEXTCLOUD_ADMIN_USER: "{{ .NC_ADMIN_USER }}"
        NEXTCLOUD_ADMIN_PASSWORD: "{{ .NC_ADMIN_PASS }}"
        NEXTCLOUD_DATA_DIR: "/var/www/html/data"
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: nextcloud
