---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nextcloud
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      nextcloud:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/nextcloud
              tag: latest
            env:
              PGID: "100"
              PUID: "1041"
              TZ: "America/Chicago"
    service:
      app:
        controller: nextcloud
        ports:
          http:
            port: 443
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.the-nebula.xyz
        hosts:
          - host: "cloud.the-nebula.xyz"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: nextcloud
        globalMounts:
          - path: /config
      data:
        type: nfs
        server: 192.168.3.5
        path: /eros/Apps/Nextcloud
        globalMounts:
          - path: /data
