---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: scrypted
spec:
  interval: 30m
  chart:
    spec:
      chart: scrypted
      version: 0.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      repository: koush/scrypted
      tag: v0.111.0-jammy-lite
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        ports:
          http:
            port: &port 11080
            primary: true
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: "scrypted.the-nebula.xyz"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: scrypted
                  port: *port
