---
# Note: Authelia vars should be escaped with $${VAR_NAME} to avoid interpolation by Flux
authentication_backend:
  ldap:
    address: ldap://lldap.default.svc.cluster.local:3890
    implementation: custom
    timeout: 5s
    start_tls: false
    base_dn: dc=the-nebula,dc=xyz
    additional_users_dn: ou=people
    users_filter: "(&({username_attribute}={input})(objectClass=person))"
    additional_groups_dn: ou=groups
    groups_filter: "(member={dn})"
    user: cn=admin,ou=people,dc=the-nebula,dc=xyz
    attributes:
      username: uid
      display_name: displayName
      group_name: cn
      mail: mail
      member_of: memberOf
  password_reset:
    disable: true
  refresh_interval: 1m

session:
  same_site: lax
  inactivity: 5m
  expiration: 1h
  remember_me: 1M
  cookies:
    - name: kinzoku_session
      domain: the-nebula.xyz
      authelia_url: https://auth.the-nebula.xyz
      default_redirection_url: https://the-nebula.xyz
  redis:
    database_index: 2
    host: dragonfly.database.svc.cluster.local

notifier:
  disable_startup_check: true
  smtp:
    address: smtp-relay.default.svc.cluster.local:25
    sender: Authelia <authelia@hamza.casa>
    disable_require_tls: true

totp:
  disable: false
  issuer: authelia.com

webauthn:
  disable: true

duo_api:
  disable: true

access_control:
  default_policy: two_factor
  networks:
    - name: internal
      networks: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
  rules: []

identity_providers:
  oidc:
    cors:
      endpoints: ["authorization", "token", "revocation", "introspection"]
      allowed_origins_from_client_redirect_uris: true
    clients:
      - client_name: Grafana
        client_id: "$${GRAFANA_OAUTH_CLIENT_ID}"
        client_secret: "$${GRAFANA_OAUTH_CLIENT_SECRET}"
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris: ["https://grafana.the-nebula.xyz/login/generic_oauth"]
        userinfo_signed_response_alg: none
      - client_name: MinIO
        client_id: "$${MINIO_OAUTH_CLIENT_ID}"
        client_secret: "$${MINIO_OAUTH_CLIENT_SECRET}"
        public: false
        authorization_policy: two_factor
        pre_configured_consent_duration: 1y
        scopes: ["openid", "profile", "groups", "email"]
        redirect_uris: ["https://minio.the-nebula.xyz/oauth_callback"]
        userinfo_signed_response_alg: none
