apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:49+UKhkH6Ge+yyTXTBbHTsniSgLbAbBlnIWxvr+4wZMbmjtqRd5Tcg==,iv:VsE5n/V0mqM1+bBSjnO//JIWgDc1UMJNoTb82MY5V0Q=,tag:15oijFu8DjEVevd4DYJ0Gg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age109u0hhummvyua8h6ep67mmlucus5cwwp3aq2zkfsgw7mewartdjqdpjn4x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZTg2ODN2bTBHUTl3akla
            NHFwYUFTemRCbjlhcUZob0FtU2ZSdENSZkhZCmttNkhsUHIyUmdvUUtUUW55OURP
            cWROc3JNMGZpN0dXZXJ5RzZvMWJjZzgKLS0tIGx3R2JWanR3anN2c2EybmF2UG5y
            SjVCNzZXUzBuRnF2SUxTMXlXWVFsODgKTgpnkXyW7At9LV1jZ3eGRccds9w3yH/W
            BoXEkILeRJqBXYl4mz1EHh2q+Lhx9iAs9HzzdXfdWFdHKGWcO6l/YQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-11T23:55:30Z"
    mac: ENC[AES256_GCM,data:s515OZjmsHTMfjz04kuqRoU5wg/jt7hvx2kojewoPaSg0ToowYGgc3wIcyZpquYk7yB0lSy4u7Zw8e3Fgx7s5z98shvOZytLn5+5C80utr2tb/x/Q813ODzvMT2yYstNpt9x3RqrhzR3WwNryRgxyAq/463IpnqJojLVmMgFPOU=,iv:Cyju+kQhORj4WNMJfQzjg1znVFbGQTufsUqq32Nhjfs=,tag:ufl19WIVfuwLmPIUvUye/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
