apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:CsOxJghKw4JwY512zjJb/FvhBIW9tZq3CJ4JhtcWTSRlGJcxGEEqCw==,iv:Vnizk+4qJtzTLDbF+QuE18yJOhcqpSatngO4nTy6Zvc=,tag:XaAPwB4KVtU1X5IKUZIIMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age109u0hhummvyua8h6ep67mmlucus5cwwp3aq2zkfsgw7mewartdjqdpjn4x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMWw5YjVzZnQraWN3S0Jk
            UjFaMjlCTFo0cE52V0lHRTArbDl3WndiblQ0CkgyNlB6NHdoV0xQSXN0Tk5ET3VO
            MkNIcEFTMExoT0xEeXJ4UGtyMVRZd2sKLS0tIFREaVlJMmtVRTJnUEhZN1N4cEU1
            dGl0a0JwNnBWWktyOFlpbDVpNFl0R00KWwkLSyP1Mw7eNm7U6MOzesGI7DFhgCAO
            KA1+Xb6I+A7SCfJkg4PVwa88APfR0QLJRqTU9B0ZpTmGKVK2/RjJRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-04T23:07:46Z"
    mac: ENC[AES256_GCM,data:CW0WrddeoL2MI2TcIpwG9qQYYah7Yr1oJ5ibFKW5HURqlx6PlLDdsGPpogbs5ZfQgnM2BxgIMK/r60vdFr66UM5++Xs2dkelrVnhG6tU8DJ0rfWfncURx0zpS+6BXPu8ZOqyyaIwlfws3roM2LuljDdF3CSci/jD/fyBiB8dLM4=,iv:gX2sP6EnR1gQKl0o5CT/HfbO279foR1BZkpXkt+iXCY=,tag:cuYARsiZxjIJ/u4zLExRtw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
