apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:cWgOXhGx/emu3OQOKYB616JO5r/A644wsa3EK8ZCoo1bFDpXMAdFOQ==,iv:oESRYucQBK6IT8kIMzOu0LGphGWFDe/bn8k/ejjoPzU=,tag:S58QqtCjnoNGNqX6F8hdRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age109u0hhummvyua8h6ep67mmlucus5cwwp3aq2zkfsgw7mewartdjqdpjn4x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNmZiMm9RcWxwalZ3Qk9y
            L01GN2xhb0szRlVYSjhQTmkxcEFBdUJlQm04CnZJSnpHS243Ty94TU9qWWxNaG9s
            cnJEbjJHdTNibFRCWXBlM1I0QVYxUEkKLS0tIHB1WjRhbWhtN1I4UllOblp5OVdp
            T0hPblltdEJXM2pwSDcvL0hHQWh3cVEK6HSX4d5ZQctiyZOFaDBZnsYRUZ6oBekO
            safjry+entCHFYzg9PlWsPIrpWAlWcyeKcp/rPX5LznZqEhDVGCjgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-07T22:33:06Z"
    mac: ENC[AES256_GCM,data:aUtt3SR7RE2dHoYcmE9Uhs2Wg1m3Tk0jpEJ7cIrTBr+umnzUa70Sfu8H3k2ul1WKWfSAvTkIvC4MKaXVWS55UkFPb6V7Mjs70nH6JsiOt3rd4dGzFzffRITU4JeOdSMqUeDisMPRduzetSrgIXe1fQlWuhNZTNST3agm4vgKRYI=,iv:1U7+WUjQbf5iADopbBtu0cuCete3jS8vzkJtsmcFLd4=,tag:a9QTbusWexiirXl5FDSVYQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
