apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:KIZN0jWOfTaJJcBgXU4HQcN3aWtYPJ7GKqeIV4vdXhzBI28CdgTsLg==,iv:o3SM3nxkmqr0CE1vKLDyRweqX9CnifDMikSoghCWQl4=,tag:1rvAOeXUSAYtNeI9/mbLrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age109u0hhummvyua8h6ep67mmlucus5cwwp3aq2zkfsgw7mewartdjqdpjn4x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUL25ia00rYi9qNWh6ZHhJ
            RUN6SDl5LzZMYnBtd0hGWHdEMFQ4TStQUVVNCjgydHVJQ21CbEZBTnovaCt6cEJT
            OEU3TSthR1V3UFE0dW9WdmJJektnTGMKLS0tIE4xRUZwS1g0Yk9UQllzazNUdTFR
            RzZST0FKaGJHMEFCL2lFYXpJMDhRZ3MKRDL67b4CJXA1khR6DZD0PdYwAnb9ajJ6
            0KA/PoGXxQQtLowL45FkhuPFB5ABRDfxRI9D3t8zs5L2/KAqZlUiTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-26T16:01:39Z"
    mac: ENC[AES256_GCM,data:TdXzuu4HLEiYSQYiPfsWvJvja9B8fxJZ8kj94ArV3TLYJyFnkFJD7jPgBEfognlF9FyGAn/88IirKFiti9Q4zkDVXIa9zl836FL1yPYZ9aLNDbjVituzfRp6moCH2t9JxOR/+M3pa6bT0AXIuD3Xjjs3PX62ftAoQwDkjvli5/c=,iv:TJa0vzTtDQRN/9dMWz6WN4110qB/27UG5iKnM5IkokQ=,tag:Nr4ZJLsYDvZJlJ6JbB8qlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
