---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: shlink-webui
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      shlink:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/shlinkio/shlink-web-client
              tag: stable
            envFrom:
              - secretRef:
                  name: shlink-webui-secret
    service:
      app:
        controller: shlink
        ports:
          http:
            port: 8080
    ingress:
      app:
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/auth-method: "GET"
          nginx.ingress.kubernetes.io/auth-url: "http://authelia.default.svc.cluster.local/api/authz/auth-request"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.the-nebula.xyz?rm=$request_method"
          nginx.ingress.kubernetes.io/auth-response-headers: "Remote-User,Remote-Name,Remote-Groups,Remote-Email"
        hosts:
          - host: "ldash.the-nebula.xyz"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
