---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nullpointer
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: 0x0-secret
    template:
      engineVersion: v2
      data:
        0X0_DB_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        0X0_DB_NAME: &dbName "{{ .NP_DB_NAME }}"
        0X0_DB_USER: &dbUser "{{ .NP_DB_USER }}"
        0X0_DB_PASS: &dbPass "{{ .NP_DB_PASSWORD }}"
        DATABASE_URI: "postgresql://{{ .NP_DB_USER }}:{{ .NP_DB_PASSWORD }}@postgres16-rw.database.svc.cluster.local/{{ .NP_DB_NAME }}"
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: nullpointer
