---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./smtp-relay/ks.yaml
  - ./authelia/ks.yaml
  - ./tf-controller/ks.yaml
  - ./shlink/ks.yaml
  - ./lldap/ks.yaml
  - ./0x0/ks.yaml
