---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tf-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: tf-controller
      version: "0.16.0-rc.4"
      sourceRef:
        kind: HelmRepository
        name: tf-controller
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    replicaCount: 3
    concurrency: 24
    resources:
      limits:
        cpu: 100m
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 64Mi
    caCertValidityDuration: 24h
    certRotationCheckFrequency: 30m
    image:
      tag: v0.16.0-rc.4
    runner:
      image:
        tag: v0.16.0-rc.4
      grpc:
        maxMessageSize: 30
