---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./thanos/ks.yaml
  - ./gatus/ks.yaml
  - ./grafana/ks.yaml
  - ./vector/ks.yaml
  - ./loki/ks.yaml
