apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:/2XP8AtsVQcllfENFHBQGuyfpjQbO+VNvU/VI2P3caQeYWmcnzE+0SfbN5qR/PYqTozAHbNqmGwERKwOq/5SpGxe9X1bgEYRiVRq6pB/09DappcN9VcY5g5tPUxqpg==,iv:LFy6KtJMaBX1xxJYNkM5x20ZjuyKaejLqQXtwraR/48=,tag:le3ayjpJiT83EDAHSkcLJg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:UmgOTcbthhbWtjYSveg=,iv:wzsgS7F6BYI2Dvqrd04tSP59I/yXsH2kImMq5QMNlaA=,tag:2rb0vxnQp08N9LoUzEneZA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:GZ8PEiA+LA+HoN+HOrh6PxNHMHTPpQ==,iv:I/fR0yMS4cgIqsMp5tefuiZ412F9+PASoOfMaTKCQCc=,tag:/UnO/pt97cL7Q+yQe9v6og==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:I0AjHuGRzcTviiyZtJsAl8qyEOwJKEMkHiKZcKUdnr/hLAGp,iv:C8lzXgBPBFHTpjIOHrai+UogNgLSE6O0qsTIcD+0A28=,tag:pFc38WQ3MqFu1BtuHFCLvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age109u0hhummvyua8h6ep67mmlucus5cwwp3aq2zkfsgw7mewartdjqdpjn4x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQ25Qb0hBNkJBTEx0akZE
            Vm5lTWora0dqajZsQ0YwQm1MWHVVQnVQUG1rCmZ1KzVPMkFMMTA4eVcrN1UvS1JJ
            T0VvSFcxem15NTUyL0NLcVR4bWNWdGsKLS0tIC8za0k0MWVhTVI4U1RPVURoSHE0
            aWV5Tzd3OVl1RFh5MXkvUzNGeG4wancKN7LwYmyHHej7EFo1oXaIV/4mUauTyGJ5
            0dgFPsMHfmiPrfVuF88zZ3Y2zy4QehBEKLgpvyHerfqlOD51N9h6ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-12T21:23:28Z"
    mac: ENC[AES256_GCM,data:HAsYUhCUMDWTc4tqrNJCwnxP9XyydGCJ12YLXVOJCRoojZdogc7KB0Kz34J+zhn3Zcb6QZpSclzLlPiS/nESjeRzUUw4qE+l7NJW0ggjcOjoDfc5pVIgScGNbXsWt6Drx6owgsM9qO/Q1wwneBZa/FsfVPnXlqhNmiKcJHqZyCU=,iv:TJaYv91nQLXGD4Ggxg5d3Z3n4NCaQq3+mgl6S6QptC4=,tag:a5tqtS5iXf79o/ZOgMiaaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
