apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:Lod5pm27fwn5SkESmtZZh8ZIoZ5ASy+SYaihxHaCGKvVMIcD0YEBaSasz4upev/tXZOKBcMI2TRQH10LsbjKO8qNfyAW4BZPdpdO1EVBep1uVTbNj+1cAfj3r9zGiQ==,iv:jpo/lpxjQtBbsT3VsVBRMajsJ0E+/HmwrZzb/Pseoyg=,tag:pABXcjAARqOz/DXP+k/dFQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:3r83jooVJsJain7ngu4=,iv:X0nQzOt6ow+bxaLnciacqfsKqpUhWrpvHybMJV3UUh4=,tag:HwyXXMAMJvaysVYfTEcwfg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:HiRk1XGwMnjtC6FdsaGhdkL3xHp5kQ==,iv:v5wJd5qcMZlURWpAXJwKwdLH2y+9ZyHJ6FI0aRJNgec=,tag:uGx3mvSBuNExJz7l9M6AsA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:c7eJYMmgJjqSpbqnzkDmnrg9hVG2YQyAIztNeu6GYPxpSn9u,iv:NRS8K5QPZMdGnEXVDsJe+nEcWz3KTr8EZERoCdZG9FY=,tag:AA8b8cOw0xXvVq9Ua5qGSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age109u0hhummvyua8h6ep67mmlucus5cwwp3aq2zkfsgw7mewartdjqdpjn4x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCekpHN3ZFMEw5MThZdld5
            UHAzZm11MzlWcGROc2hpSmtIN0JwcGgyTGxNClVWekx4LytwR0tWMlZpcXBISExj
            RWhpZmxhdVRFQ2JrK3Z1bFFxOTYyWTgKLS0tIElXL2NjVEluR1F6YlU2WG11Y2g1
            MFc0dWZzS3RSWGZ1aHNpeWU5bGRhdkUKufeuHeENJU/xpMkUqfZ8UN/pNjfov4Yh
            1dt7OLtn1QGp/1KmZyHUqmjtzRpCNGjohIInAeklnXCCCUHanSTrwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-04T23:07:46Z"
    mac: ENC[AES256_GCM,data:PxZ5qlQ7gKn5XuF+DRq8l5Dy+vnrvmPNiE2YMZpNww0hsQazzVshWoexPTjakr2l0YCBB8DjlMjML08EYRl27zoixbbWv/0SkbM88HiOb8XfgJU65pzx4SDCPdXYfxbGCchTAIccs4PtiNEJq9g5WTVD68pIh+45uAUbDVGTS4k=,iv:10xuyls2toHQ2Robw7sw/ntfi9sltxObk+ed4pJed6A=,tag:EkoGTvdrplhqJjSXRp0rPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
