apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:zT88OCtB8Q/AnOfqcfML3pGfWfnXIh0CPAzZZHwEkwoKacAv,iv:7gniBwn3RUKTIQouPXgzEbrdzW8HK0Nib//zq2h/TvY=,tag:ge64xlkL13qoPpn1g5AboQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:eAfxssOnZrAKbxjVGCDoWsbwIAxtalGcpCOfQGKf3NEwpr1fUyvZ36uBphfcRcWGDvOcttw1W3hVdOG0nv1CYcxrEsg+UY0TV1/mqglmMLGvM1srF87dTrVuiidfcCWcdkCPRW6/5h7OxdxtvivclxjZYrJY3uEyaNjVv0Iegtwb/vS+IKMzDGCykB4EoWalXihmztOB614tV/xif0+DWa3OaYiLZPKxye9mvSI/lA==,iv:RcsFQRDkCyYKRLcGuz2yaNnU9mGTyziiLLI1PVmqzyU=,tag:iYwIcS/4jLQxFDXIZzaC5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age109u0hhummvyua8h6ep67mmlucus5cwwp3aq2zkfsgw7mewartdjqdpjn4x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQUxBWGVLK0lsTWlFK2ly
            WEQrWHZ0QVF4MkV3MGIvN1FPWEN6V1NpeGdrCkFDaVNiVHVuVXpnVmhvZWdDOHNL
            U0wvQTVFZ0wrSllVL1pXdUY3d1NxRTAKLS0tIFE5NmxrUXBia1ErNzRzNXcrMWJO
            TU50L3JBWE5LVTlnYlpBQ1lEcDdXd0kKicOYO8p1rwPJgG/z36dEJQPk2giRD6vF
            AYjLqrJLQDnoFzPfssqIW6+kqKWOor0AbaVVbu3Qf8IkZ1WMhJLxTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-27T22:21:23Z"
    mac: ENC[AES256_GCM,data:THluwD44JdrNt6o+y4So6GMQJ/7TC6dw3s4gWkube1nykc6rb6DLK3rVpq+RFYokj6eCSEW2B4RtrOAhndoqwQDmANst3I/J0SvYWpONoLo29+O8qh6ndsiHRfRwhdcKSWfAFqzzbGrCjW3USvSf+hqmcQFElaz5FJuCllOqU3s=,iv:THT/H0qQVgbflkHApruRqW/RgDTUuLJJhxqhLAPZNTc=,tag:4aYG7fLRhty7z63Vkqm5MA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
