apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:HEh9ff5PU5ZWW0fxRBt7mKET/QiU0jM/Zn576MbkBhQ=,iv:vWRD1az0mZS1VbZFvD/WGZ+EIkDSmO6gP55dPIe2xOA=,tag:Ecge/Fs1nBjLzoxOsxAu2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age109u0hhummvyua8h6ep67mmlucus5cwwp3aq2zkfsgw7mewartdjqdpjn4x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WVlvK0Z5TStWdWh1ZU5O
            ZEJkc3NxN1BqYTB2SUhMN1BJcjY3amVRVVZzCjRJMWsveHdxUlNkR3ZEbjh6UDd5
            dlNIaVV3QlFQK1dqcURzWkZlVDlET28KLS0tIGJNRTMzeEhpRExVUEFiRHlKcU9u
            QndnWW12QXpTOVFGT0IyNy95WW9VcW8KEbJQUfd5heoJBrB2W3ICHj3MyiwF6fVI
            Y13L8SS7mqJ2Y5AM3NCeLqbN+zuvIdfTq7RgPIszIzNvvUgfTuG0Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-26T17:05:05Z"
    mac: ENC[AES256_GCM,data:NzduntTwwhLqNhGOuaIXGa1jpJ65xspn0ydDZaDuBdfnL9jFMb8/wjO7s8z7WUzAuhTUSvKdBEmot7B8p8x5ukUUNKtgHNOelAt9+jlEas2MyEWGfWxzIxt9rX7tcQv5zlBwBkfJzFJ7+Q4YFDPRAoXYlN8VT4TtfsOBY2dQoW0=,iv:uZ4z5nmG0UNYPlkY/gO8cOwxCsx1iqeu1uUHXUWqR+A=,tag:oItWAp8ApI9tdJwhD6PGpQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
