apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:wa3V4N2FZXtUBOIy8uf2M35M1qCcSssogu/41bcx6cY=,iv:V/7FTLA7SCpfR2jWoGvq+RHa0/rnptE8b6GL1QZKEgU=,tag:8hIOqXY6VPu+EqNj4su/8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age109u0hhummvyua8h6ep67mmlucus5cwwp3aq2zkfsgw7mewartdjqdpjn4x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Nko4alFlbmJ2Y0pmRUJQ
            a2orZ1l2Vzg4eHVESlhTbG5KTHlpejFRSTBzCkdpQjBTVTZKR1VNZFR2MVZGendF
            NlRZU3F1N1lSWEo2V0o1VFpKaUUzWGMKLS0tIEc1S3Q0V0xPSlB3QUFCNktlRUg2
            SUF2MnpjMHlMNnBJaWhsM1gwbjdGR28KiYpYuDG9EgeMwcgEZ/aI4OMKJG4d2vO6
            IFelrFtFVnopQZOv2152eNxkzcKOKtCttQ/iWg9mnUB62tYbJQQGYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-26T16:01:39Z"
    mac: ENC[AES256_GCM,data:+2EoXz7I38Iej6s5pVvfQOqSk5Pwp86Q7k78Sva8NZKSLBZSeMpMsccMBTiWE5LEcojoDY3SJ7NVMA0onyBiFkuiGZdqW9c4N4Kj7Eb9UC2a0VwkoRCZZZ94AuTq9lvg0b93yCGHRZGESn144XLOautrfrS1aucUrwnBbaXuup8=,iv:7RWofD/Clnb47S7qB+jXYhBGkJY/CuQ4Pmw3/jLHWIA=,tag:fccAfpbXJcoG/KVZdLVhsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
