apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:UKau6KLZY6G5VF52hV58Y7EWisYEE9J67MOsUJ/hWY0=,iv:56jkx3/0bL5Q2dpxbzuBXrYyvlOLxkAVd/HavPiSkYo=,tag:zW4XE1GbrzNLqhfz2Kjm3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age109u0hhummvyua8h6ep67mmlucus5cwwp3aq2zkfsgw7mewartdjqdpjn4x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzd0FYNHJPaWcwZUE5UXFt
            NldGWCs2VlpkbjcyL1liU3BlVFZ3YlI5bFFjClRFL1pvQkF0aE5LeHZrVnlPVFBw
            U3Jab3RwcFJ2TEZEaHBZOXlmZkhRYTgKLS0tIHRFSDZDV2FRcDdJNlJkQ1kxVFYr
            bGJ0M0lneGVtN01FQVZhRXVEaEo2ZmMKztv/9IkUkKiW66vFwFvqluSdjQSPR21+
            0RlBAzVdwwnk9oyFuwSs71m+8hE+QWheq03c0iA7uuXEllZcY1qI8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-07T22:33:06Z"
    mac: ENC[AES256_GCM,data:BHOycU4PsDuuK4DBjAz/EJyX/9+86RJsZ+ciN0O8R9ugzMl1OoEv2VwGnysrdGK1gVmAG3Z9iIzLlX0D+OZj8LHc3p+pIkZ+n+DtZc/TJIhsgeQb0QEj8xEtj4GSaQqrPi4N877sUU/1FTkiGC69s0J/h6QjvK1vNevJHuH+FHM=,iv:CmRRn+Y11auwE+ZPIWfM0tnUVDsuPLHeWJ3B3g41P9k=,tag:/eY9g973GwKy4DzLqSx8EQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
