---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: bitwarden-cli
  namespace: external-secrets
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      bitwarden-cli:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          cli:
            image:
              repository: ghcr.io/charlesthomas/bitwarden-cli
              tag: 2023.12.1
            env:
              BW_HOST:
                valueFrom:
                  secretKeyRef:
                    name: bitwarden-cli-secret
                    key: BW_HOST
              BW_USER:
                valueFrom:
                  secretKeyRef:
                    name: bitwarden-cli-secret
                    key: BW_USERNAME
              BW_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: bitwarden-cli-secret
                    key: BW_PASSWORD
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - wget
                      - -q
                      - http://127.0.0.1:8087/sync?force=true
                      - --post-data=''
                  initialDelaySeconds: 20
                  failureThreshold: 3
                  timeoutSeconds: 1
                  periodSeconds: 120
              readiness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 8087
                  initialDelaySeconds: 20
                  failureThreshold: 3
                  timeoutSeconds: 1
                  periodSeconds: 10
              startup:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 8087
                  initialDelaySeconds: 10
                  failureThreshold: 30
                  timeoutSeconds: 1
                  periodSeconds: 5
    service:
      main:
        controller: bitwarden-cli
        ports:
          http:
            port: 8087
            protocol: TCP
    networkpolicies:
      es-2-bwcli:
        policyTypes:
          - Ingress
        podSelector:
          matchLabels:
            app.kubernetes.io/instance: bitwarden-cli
            app.kubernetes.io/name: bitwarden-cli
        rules:
          ingress:
            - from:
                - podSelector:
                    matchLabels:
                      app.kubernetes.io/instance: external-secrets
                      app.kubernetes.io/name: external-secrets
