---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: homepage
      version: 1.2.3
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: v0.9.2
    enableRbac: true
    serviceAccount:
      name: homepage
      create: true
    service:
      main:
        ports:
          http:
            port: 3000
    controller:
      strategy: RollingUpdate
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
    ingress:
      main:
        enabled: true
        ingressClassName: "internal"
        hosts:
          - host: &host "home.the-nebula.xyz"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    config:
      bookmarks:
        - Developer:
            - GitHub:
                - abbr: GH
                  href: https://github.com/kinzoku-dev
      services:
        - Monitoring:
            - Gatus:
                href: &gatusUrl https://status.the-nebula.xyz
                description: Uptime dashboard
                icon: gatus.svg
                widget:
                  type: gatus
                  url: *gatusUrl
      widgets:
        - resources:
            backend: kubernetes
            expanded: true
            cpu: true
            memory: true
        - search:
            provider: brave
            target: _blank
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: true
              label: "cluster"
            nodes:
              show: true
              cpu: true
              memory: true
              showLabel: true
      kubernetes:
        mode: cluster
    persistence:
      logs:
        enabled: true
        type: emptyDir
        mountPath: /app/config/logs
